/** Generate reviewable LOCAL-ONLY SQL from versioned JSON; never connects to a database. */
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

const root = fileURLToPath(new URL('../../', import.meta.url));
const slug = z.string().regex(/^[a-z0-9-]+$/);
const districtSchema = z.object({
  slug,
  nameAr: z.string().min(1),
  nameEn: z.string().min(1),
  areaSlug: slug,
  referenceVerified: z.boolean(),
  enabled: z.boolean(),
});
const referenceSchema = z.object({
  schemaVersion: z.literal(1),
  country: z.object({ code: z.string().length(2), nameAr: z.string(), nameEn: z.string() }),
  governorate: z.object({ slug, nameAr: z.string(), nameEn: z.string() }),
  areas: z.array(z.object({ slug, nameAr: z.string(), nameEn: z.string() })),
  districts: z.array(districtSchema),
  demoDistricts: z.array(districtSchema),
});
const contactsSchema = z.object({
  schemaVersion: z.literal(1),
  mode: z.literal('test'),
  districts: z.array(
    z.object({
      districtSlug: slug,
      verified: z.literal(false),
      endpoints: z.array(
        z.object({
          type: z.enum(['primary', 'technology_center', 'operations', 'area', 'escalation']),
          email: z
            .email()
            .refine((value) => value.endsWith('.invalid'), 'Demo contacts must use .invalid'),
          enabled: z.boolean(),
        }),
      ),
    }),
  ),
});
const point = z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]);
const ring = z
  .array(point)
  .min(4)
  .refine(
    (points) => JSON.stringify(points[0]) === JSON.stringify(points.at(-1)),
    'Ring must close',
  );
const polygon = z.array(ring).min(1);
export const boundarySchema = z.object({
  type: z.literal('FeatureCollection'),
  features: z
    .array(
      z.object({
        type: z.literal('Feature'),
        properties: z.object({
          districtSlug: slug,
          version: z.string().min(1),
          isSynthetic: z.boolean(),
          active: z.boolean(),
          sourceNote: z.string().min(1),
          license: z.string().min(1),
          sourceUrl: z.url().optional(),
        }),
        geometry: z.discriminatedUnion('type', [
          z.object({ type: z.literal('Polygon'), coordinates: polygon }),
          z.object({ type: z.literal('MultiPolygon'), coordinates: z.array(polygon).min(1) }),
        ]),
      }),
    )
    .min(1),
});

function literal(value: string): string {
  return "'" + value.replaceAll("'", "''") + "'";
}
function id(value: string): string {
  const hash = createHash('sha256').update(`balaa-demo-v1:${value}`).digest('hex');
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
}
async function readJson(name: string): Promise<unknown> {
  return JSON.parse(await readFile(`${root}/data/${name}`, 'utf8'));
}

const reference = referenceSchema.parse(await readJson('cairo-districts.json'));
const contacts = contactsSchema.parse(await readJson('cairo-district-contacts.json'));
const boundaries = boundarySchema.parse(await readJson('cairo-district-boundaries.geojson'));
const allDistricts = [...reference.districts, ...reference.demoDistricts];
const knownDistricts = new Set(allDistricts.map((d) => d.slug));
if (knownDistricts.size !== allDistricts.length) throw new Error('Duplicate district slugs');
if (reference.districts.length !== 38)
  throw new Error('Expected 38 Cairo reference districts plus separate demonstration fixtures');
for (const d of allDistricts)
  if (!reference.areas.some((area) => area.slug === d.areaSlug))
    throw new Error(`Unknown area ${d.areaSlug}`);
for (const c of contacts.districts)
  if (!knownDistricts.has(c.districtSlug))
    throw new Error(`Unknown contact district ${c.districtSlug}`);
for (const feature of boundaries.features) {
  if (!knownDistricts.has(feature.properties.districtSlug))
    throw new Error('Boundary references unknown district');
  if (!feature.properties.isSynthetic)
    throw new Error('Local demo generator only accepts explicitly synthetic boundaries');
}
if (process.argv.includes('--validate-only')) {
  console.log(
    `Validated ${reference.districts.length} reference districts + ${reference.demoDistricts.length} demo area, ${boundaries.features.length} synthetic boundaries, ${contacts.districts.length} contact configurations.`,
  );
} else {
  const rows: string[] = [
    '-- GENERATED by supabase/seed/generate-seed.ts from data/*.json; local demo ONLY.',
    '-- WARNING: this enables mock identity and synthetic boundaries. Never run on a production project.',
    'begin;',
    'update private.runtime_settings set demo_identity_enabled=true, synthetic_boundaries_enabled=true where singleton;',
  ];
  const countryId = literal(id(`country:${reference.country.code}`));
  const governorateId = literal(id(`governorate:${reference.governorate.slug}`));
  rows.push(
    `insert into public.countries(id,code,name_ar,name_en) values(${countryId},${literal(reference.country.code)},${literal(reference.country.nameAr)},${literal(reference.country.nameEn)}) on conflict(id) do nothing;`,
  );
  rows.push(
    `insert into public.governorates(id,country_id,slug,name_ar,name_en) values(${governorateId},${countryId},${literal(reference.governorate.slug)},${literal(reference.governorate.nameAr)},${literal(reference.governorate.nameEn)}) on conflict(id) do nothing;`,
  );
  for (const a of reference.areas)
    rows.push(
      `insert into public.administrative_areas(id,governorate_id,slug,name_ar,name_en) values(${literal(id(`area:${a.slug}`))},${governorateId},${literal(a.slug)},${literal(a.nameAr)},${literal(a.nameEn)}) on conflict(id) do nothing;`,
    );
  for (const d of allDistricts) {
    const districtId = literal(id(`district:${d.slug}`));
    const authorityId = literal(id(`authority:${d.slug}`));
    rows.push(
      `insert into public.districts(id,governorate_id,administrative_area_id,slug,name_ar,name_en,enabled,reference_verified) values(${districtId},${governorateId},${literal(id(`area:${d.areaSlug}`))},${literal(d.slug)},${literal(d.nameAr)},${literal(d.nameEn)},${d.enabled},false) on conflict(id) do nothing;`,
    );
    rows.push(
      `insert into public.authorities(id,district_id,name_ar,name_en,enabled,is_demo) values(${authorityId},${districtId},${literal(`جهة تجريبية — ${d.nameAr}`)},${literal(`DEMO authority — ${d.nameEn}`)},true,true) on conflict(id) do nothing;`,
    );
    rows.push(
      `insert into public.routing_rules(district_id,endpoint_type,enabled) values(${districtId},'primary',${d.enabled}) on conflict(district_id) do nothing;`,
    );
  }
  for (const configuration of contacts.districts)
    for (const endpoint of configuration.endpoints) {
      rows.push(
        `insert into public.authority_contacts(authority_id,endpoint_type,email,enabled,is_test) values(${literal(id(`authority:${configuration.districtSlug}`))},${literal(endpoint.type)},${literal(endpoint.email)},${endpoint.enabled},true) on conflict(authority_id,endpoint_type,email) do nothing;`,
      );
    }
  for (const feature of boundaries.features) {
    const p = feature.properties;
    rows.push(
      `insert into public.district_boundaries(id,district_id,version,geom,source_note,license,is_synthetic,active) values(${literal(id(`boundary:${p.districtSlug}:${p.version}`))},${literal(id(`district:${p.districtSlug}`))},${literal(p.version)},extensions.st_multi(extensions.st_setsrid(extensions.st_geomfromgeojson(${literal(JSON.stringify(feature.geometry))}),4326)),${literal(p.sourceNote)},${literal(p.license)},true,${p.active}) on conflict(district_id,version) do nothing;`,
    );
  }
  const categories = [
    ['manhole', 'بلاعة مفتوحة أو مكسورة', 'Broken/open manhole'],
    ['pothole', 'حفرة في الطريق', 'Pothole'],
    ['speed-bump', 'مطب تالف أو مكسور', 'Damaged speed bump'],
    ['road-surface', 'تلف في الأسفلت', 'Road surface damage'],
    ['pavement', 'تلف في الرصيف', 'Pavement damage'],
    ['water', 'مياه أو صرف صحي', 'Water/sewage issue'],
    ['obstruction', 'عائق في الطريق', 'Road obstruction'],
    ['lighting', 'إنارة طريق', 'Street-lighting issue'],
    ['waste', 'مخلفات أو قمامة', 'Waste'],
    ['other', 'أخرى', 'Other'],
  ] as const;
  categories.forEach(([categorySlug, ar, en], order) =>
    rows.push(
      `insert into public.categories(id,slug,name_ar,name_en,display_order) values(${literal(id(`category:${categorySlug}`))},${literal(categorySlug)},${literal(ar)},${literal(en)},${order}) on conflict(slug) do nothing;`,
    ),
  );
  rows.push('commit;');
  await writeFile(`${root}/supabase/seed/seed.sql`, rows.join('\n') + '\n', 'utf8');
  console.log('Generated supabase/seed/seed.sql (local demo only; no database connection).');
}
